/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.nulibrarysystem;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Jianna Ramos
 */
public class LoginPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginPage.class.getName());

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        aboutUsButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FNField = new javax.swing.JTextField();
        SNField = new javax.swing.JTextField();
        PWField = new javax.swing.JPasswordField();
        course = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jianna Ramos\\Documents\\NetBeansProjects\\OOP_RAMOS_ACTIVITY2\\src\\images\\Untitled design.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 750));

        jPanel1.setBackground(new java.awt.Color(8, 8, 54));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 209, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginButton.setBackground(new java.awt.Color(255, 209, 0));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginButton.setText("LOGIN");
        loginButton.setBorder(null);
        loginButton.setBorderPainted(false);
        loginButton.addActionListener(this::loginButtonActionPerformed);
        jPanel3.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1083, 20, 70, -1));

        homeButton.setBackground(new java.awt.Color(255, 209, 0));
        homeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homeButton.setText("HOME");
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.addActionListener(this::homeButtonActionPerformed);
        jPanel3.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 20, 60, -1));

        aboutUsButton.setBackground(new java.awt.Color(255, 209, 0));
        aboutUsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aboutUsButton.setText("ABOUT US");
        aboutUsButton.setBorder(null);
        aboutUsButton.setBorderPainted(false);
        aboutUsButton.addActionListener(this::aboutUsButtonActionPerformed);
        jPanel3.add(aboutUsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 90, -1));

        jButton5.setBackground(new java.awt.Color(255, 209, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("REGISTER");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(this::jButton5ActionPerformed);
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(952, 20, 80, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jianna Ramos\\Documents\\NetBeansProjects\\NULibrarySystem\\images\\NewBanner.png")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 580, 670));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jianna Ramos\\Documents\\NetBeansProjects\\OOP_RAMOS_ACTIVITY2\\src\\images\\Untitled design.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 210, 160));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LOGIN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        FNField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FNField.setForeground(new java.awt.Color(153, 153, 153));
        FNField.setText("  USERNAME");
        FNField.setBorder(null);
        FNField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FNFieldFocusGained(evt);
            }
        });
        FNField.addActionListener(this::FNFieldActionPerformed);
        FNField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FNFieldKeyReleased(evt);
            }
        });
        jPanel1.add(FNField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 430, 30));

        SNField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SNField.setForeground(new java.awt.Color(153, 153, 153));
        SNField.setText("  STUDENT NUMBER");
        SNField.setBorder(null);
        SNField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SNFieldFocusGained(evt);
            }
        });
        SNField.addActionListener(this::SNFieldActionPerformed);
        SNField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SNFieldKeyReleased(evt);
            }
        });
        jPanel1.add(SNField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 430, 30));

        PWField.setText("jPasswordField1");
        PWField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PWFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PWFieldFocusLost(evt);
            }
        });
        PWField.addActionListener(this::PWFieldActionPerformed);
        jPanel1.add(PWField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 430, 30));

        course.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        course.setForeground(new java.awt.Color(153, 153, 153));
        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT COURSE:", " ", "BS Accountancy", "BS Nursing", "BS Architecture", "BS Information Technology", "BS Tourism Management", " " }));
        course.setBorder(null);
        course.addActionListener(this::courseActionPerformed);
        jPanel1.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 430, 30));

        jButton1.setBackground(new java.awt.Color(255, 209, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("LOGIN");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 430, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            

    }                                           

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           

    }                                          

    private void aboutUsButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              

    }                                             

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         

    }                                        

    private void FNFieldFocusGained(java.awt.event.FocusEvent evt) {                                    
        if (FNField.getText().equals("  First Name")) {
            FNField.setText("");
            FNField.setForeground(Color.BLACK);
        }
    }                                   

    private void FNFieldActionPerformed(java.awt.event.ActionEvent evt) {                                        
        String text = FNField.getText();

        if(text.length() < 2){
            JOptionPane.showMessageDialog(this, "Please Enter 2 or more characters");

        }
    }                                       

    private void FNFieldKeyReleased(java.awt.event.KeyEvent evt) {                                    
        String text =FNField.getText();

        if(text.length() < 2){
            JOptionPane.showMessageDialog(this, "Please Enter 2 or more characters");

        }
    }                                   

    private void SNFieldFocusGained(java.awt.event.FocusEvent evt) {                                    
        if (SNField.getText().equals("  Student Number")) {
            SNField.setText("");
            SNField.setForeground(Color.BLACK);
        }
    }                                   

    private void SNFieldActionPerformed(java.awt.event.ActionEvent evt) {                                        
        String text = SNField.getText();

        if (!text.matches("^09\\d*") || text.length() > 11 || !text.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Student Number must consist of numeric values only.");
        }
    }                                       

    private void SNFieldKeyReleased(java.awt.event.KeyEvent evt) {                                    
        String text =SNField.getText();

        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }                                   

    private void PWFieldFocusGained(java.awt.event.FocusEvent evt) {                                    

    }                                   

    private void PWFieldFocusLost(java.awt.event.FocusEvent evt) {                                  

    }                                 

    private void PWFieldActionPerformed(java.awt.event.ActionEvent evt) {                                        

    }                                       

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if (course.getSelectedIndex() ==0){
            JOptionPane.showMessageDialog(this, "Please select a valid course.");
            course.setSelectedIndex(0);

    }                                      

 
      
        java.awt.EventQueue.invokeLater(() -> new LoginPage().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField FNField;
    private javax.swing.JPasswordField PWField;
    private javax.swing.JTextField SNField;
    private javax.swing.JButton aboutUsButton;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginButton;
    // End of variables declaration                   
}
