/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.nulibrarysystem;

import java.awt.Color;
import javax.swing.JOptionPane;

public class RegisterPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterPage.class.getName());

    /**
     * Creates new form RegisterPage
     */
   public RegisterPage() {
       initComponents();
  
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        aboutUsButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LNField = new javax.swing.JTextField();
        PNField = new javax.swing.JTextField();
        FNField = new javax.swing.JTextField();
        EField = new javax.swing.JTextField();
        SNField = new javax.swing.JTextField();
        UNField = new javax.swing.JTextField();
        CFField = new javax.swing.JPasswordField();
        PWField = new javax.swing.JPasswordField();
        yearLevel = new javax.swing.JComboBox<>();
        course = new javax.swing.JComboBox<>();
        RegisterButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setPreferredSize(new java.awt.Dimension(1200, 750));

        jPanel1.setBackground(new java.awt.Color(8, 8, 54));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 209, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginButton.setBackground(new java.awt.Color(255, 209, 0));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginButton.setText("LOGIN");
        loginButton.setBorder(null);
        loginButton.setBorderPainted(false);
        loginButton.addActionListener(this::loginButtonActionPerformed);
        jPanel3.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1083, 20, 70, -1));

        homeButton.setBackground(new java.awt.Color(255, 209, 0));
        homeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homeButton.setText("HOME");
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.addActionListener(this::homeButtonActionPerformed);
        jPanel3.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 20, 60, -1));

        aboutUsButton.setBackground(new java.awt.Color(255, 209, 0));
        aboutUsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aboutUsButton.setText("ABOUT US");
        aboutUsButton.setBorder(null);
        aboutUsButton.setBorderPainted(false);
        aboutUsButton.addActionListener(this::aboutUsButtonActionPerformed);
        jPanel3.add(aboutUsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 90, -1));

        jButton5.setBackground(new java.awt.Color(255, 209, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("REGISTER");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(this::jButton5ActionPerformed);
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(952, 20, 80, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jianna Ramos\\Documents\\NetBeansProjects\\NULibrarySystem\\images\\NewBanner.png")); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(600, 600));
        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, 680));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jianna Ramos\\Documents\\NetBeansProjects\\OOP_RAMOS_ACTIVITY2\\src\\images\\Untitled design.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 210, 160));

        LNField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LNField.setForeground(new java.awt.Color(153, 153, 153));
        LNField.setText("  LAST NAME");
        LNField.setBorder(null);
        LNField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LNFieldFocusGained(evt);
            }
        });
        LNField.addActionListener(this::LNFieldActionPerformed);
        LNField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LNFieldKeyReleased(evt);
            }
        });
        jPanel1.add(LNField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 230, 30));

        PNField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PNField.setForeground(new java.awt.Color(153, 153, 153));
        PNField.setText(" PHONE NUMBER");
        PNField.setBorder(null);
        PNField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PNFieldFocusGained(evt);
            }
        });
        PNField.addActionListener(this::PNFieldActionPerformed);
        jPanel1.add(PNField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 230, 30));

        FNField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FNField.setForeground(new java.awt.Color(153, 153, 153));
        FNField.setText("  FIRST NAME");
        FNField.setBorder(null);
        FNField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FNFieldFocusGained(evt);
            }
        });
        FNField.addActionListener(this::FNFieldActionPerformed);
        FNField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FNFieldKeyReleased(evt);
            }
        });
        jPanel1.add(FNField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 230, 30));

        EField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EField.setForeground(new java.awt.Color(153, 153, 153));
        EField.setText("  EMAIL");
        EField.setBorder(null);
        EField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EFieldFocusGained(evt);
            }
        });
        EField.addActionListener(this::EFieldActionPerformed);
        jPanel1.add(EField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 230, 30));

        SNField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SNField.setForeground(new java.awt.Color(153, 153, 153));
        SNField.setText("  STUDENT NUMBER");
        SNField.setBorder(null);
        SNField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SNFieldFocusGained(evt);
            }
        });
        SNField.addActionListener(this::SNFieldActionPerformed);
        SNField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SNFieldKeyReleased(evt);
            }
        });
        jPanel1.add(SNField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 230, 30));

        UNField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UNField.setForeground(new java.awt.Color(153, 153, 153));
        UNField.setText("  USERNAME");
        UNField.setBorder(null);
        UNField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UNFieldFocusGained(evt);
            }
        });
        UNField.addActionListener(this::UNFieldActionPerformed);
        jPanel1.add(UNField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 230, 30));

        CFField.setText("jPasswordField1");
        CFField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CFFieldFocusGained(evt);
            }
        });
        CFField.addActionListener(this::CFFieldActionPerformed);
        jPanel1.add(CFField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, 230, 30));

        PWField.setText("jPasswordField1");
        PWField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PWFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PWFieldFocusLost(evt);
            }
        });
        PWField.addActionListener(this::PWFieldActionPerformed);
        jPanel1.add(PWField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 230, 30));

        yearLevel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yearLevel.setForeground(new java.awt.Color(153, 153, 153));
        yearLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT YEAR LEVEL:", "First Year", "Second Year", "Third Year", "Fourth Year" }));
        yearLevel.setBorder(null);
        yearLevel.addActionListener(this::yearLevelActionPerformed);
        jPanel1.add(yearLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 230, 30));

        course.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        course.setForeground(new java.awt.Color(153, 153, 153));
        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT COURSE", "BS Accountancy", "BS Nursing", "BS Architecture", "BS Information Technology", "BS Tourism Management" }));
        course.setBorder(null);
        course.addActionListener(this::courseActionPerformed);
        jPanel1.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 230, 30));

        RegisterButton.setBackground(new java.awt.Color(255, 209, 0));
        RegisterButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegisterButton.setText("REGISTER");
        RegisterButton.addActionListener(this::RegisterButtonActionPerformed);
        jPanel1.add(RegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 480, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONFIRM PASSWORD");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("REGISTER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        new LoginPage().setVisible(true);
        this.dispose();
    }                                           

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           

    }                                          

    private void aboutUsButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              

    }                                             

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         

    }                                        

    private void LNFieldActionPerformed(java.awt.event.ActionEvent evt) {                                        
    String text = LNField.getText();
            
            if(text.length() < 2){
                JOptionPane.showMessageDialog(this, "Please Enter 2 or more characters");
                
            }
            
    }                                       

    private void PNFieldActionPerformed(java.awt.event.ActionEvent evt) {                                        
    String text = PNField.getText();
            
            if (!text.matches("^09\\d*") || text.length() > 11 || !text.matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "Phone Number must be numeric, start with 09, and have a maximum of 11 digits.");
        }
    }                                       

    private void FNFieldActionPerformed(java.awt.event.ActionEvent evt) {                                        
    String text = FNField.getText();
            
            if(text.length() < 2){
                JOptionPane.showMessageDialog(this, "Please Enter 2 or more characters");
                
            }
    }                                       

    private void EFieldActionPerformed(java.awt.event.ActionEvent evt) {                                       
    String email = EField.getText().trim();
    
    
        if (!email.contains("@") || !email.contains(".")) {
            JOptionPane.showMessageDialog(this, "Email Address must follow a valid email format.");
        }
    }                                      

    private void SNFieldActionPerformed(java.awt.event.ActionEvent evt) {                                        
    String text = SNField.getText();
            
            if (!text.matches("^09\\d*") || text.length() > 11 || !text.matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "Student Number must consist of numeric values only.");
        }

    }                                       

    private void UNFieldActionPerformed(java.awt.event.ActionEvent evt) {                                        
    String text = UNField.getText();
            
            if(text.length() < 8){
                JOptionPane.showMessageDialog(this, "Username must be at least eight characters long.");
                
            }
    }                                       

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
    String firstName = FNField.getText().trim();
    String lastName = LNField.getText().trim();
    String studentNum = SNField.getText().trim();
    String phoneNum = PNField.getText().trim();
    String username = UNField.getText().trim();
    String email = EField.getText().trim();
    String password = new String(PWField.getPassword());
    String confirmPass = new String(CFField.getPassword());

    if (password.length() < 8) {
        JOptionPane.showMessageDialog(this, "Password must contain a minimum of eight characters.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return; 
    }

    
    if (!password.equals(confirmPass)) {
        JOptionPane.showMessageDialog(this, "Password and Confirm Password fields must match!", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return; 
    }
    
    StudentInfoModel student = new StudentInfoModel(
        firstName,
        lastName,
        studentNum,
        phoneNum,
        username,
        email,
        password,
        confirmPass
    );
    
    StudentStorage.students.add(student);
    
    JOptionPane.showMessageDialog(this, "SUCCESSFULLY REGISTERED!");

    new LoginPage().setVisible(true);
    
    this.dispose();
    }                                              

    private void FNFieldKeyReleased(java.awt.event.KeyEvent evt) {                                    
     String text =FNField.getText();
     
     if(text.length() < 2){
                JOptionPane.showMessageDialog(this, "Please Enter 2 or more characters");
                
            }
    }                                   

    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {                                      
    
    }                                     

    private void PWFieldActionPerformed(java.awt.event.ActionEvent evt) {                                        
    
    }                                       

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {                                       
    if (course.getSelectedIndex() ==0){
            JOptionPane.showMessageDialog(this, "Please select a valid course.");
            course.setSelectedIndex(0);
           
        }    }                                      

    private void LNFieldKeyReleased(java.awt.event.KeyEvent evt) {                                    
     String text =LNField.getText();
     
     if(text.length() < 2){
                JOptionPane.showMessageDialog(this, "Please Enter 2 or more characters");
                
            }
    }                                   

    private void SNFieldKeyReleased(java.awt.event.KeyEvent evt) {                                    
    String text =SNField.getText();
     
     char c = evt.getKeyChar();
    if (!Character.isDigit(c)) {
        evt.consume();
        }
    }                                   

    private void yearLevelActionPerformed(java.awt.event.ActionEvent evt) {                                          
    if (course.getSelectedIndex() ==0){
            JOptionPane.showMessageDialog(this, "Please select a valid year level.");
            course.setSelectedIndex(0);
           
        }    
    }                                         

    private void CFFieldActionPerformed(java.awt.event.ActionEvent evt) {                                        
   
    }                                       

    private void FNFieldFocusGained(java.awt.event.FocusEvent evt) {                                    
    if (FNField.getText().trim().equals("First Name")) {
            FNField.setText("");
            FNField.setForeground(Color.BLACK);
        }       
    }                                   

    private void LNFieldFocusGained(java.awt.event.FocusEvent evt) {                                    
    if (LNField.getText().trim().equals("Last Name")) {
            LNField.setText("");
            LNField.setForeground(Color.BLACK);
        }
    }                                   

    private void SNFieldFocusGained(java.awt.event.FocusEvent evt) {                                    
    if (SNField.getText().trim().equals("Student Number")) {
            SNField.setText("");
            SNField.setForeground(Color.BLACK);
        } 
    }                                   

    private void PNFieldFocusGained(java.awt.event.FocusEvent evt) {                                    
    if (PNField.getText().equals(" Phone Number ")) {
            PNField.setText("");
            PNField.setForeground(Color.BLACK);
        }          
    }                                   

    private void UNFieldFocusGained(java.awt.event.FocusEvent evt) {                                    
    if (!UNField.getText().equals("  Username")) {
        } else {
        UNField.setText("");
        UNField.setForeground(Color.BLACK);
        }      
    }                                   

    private void EFieldFocusGained(java.awt.event.FocusEvent evt) {                                   
    if (EField.getText().equals("  Email")) {
            EField.setText("");
            EField.setForeground(Color.BLACK);
        }
    }                                  

    private void PWFieldFocusGained(java.awt.event.FocusEvent evt) {                                    
    String pass = new String(PWField.getPassword());
    if (pass.equals("jPasswordField1") || pass.equals("Password")) {
        PWField.setText("");
        PWField.setEchoChar('●'); 
        PWField.setForeground(Color.BLACK);
    }
    }                                   

    private void PWFieldFocusLost(java.awt.event.FocusEvent evt) {                                  
        String pass = new String(PWField.getPassword());
    if (pass.isEmpty()) {
        PWField.setEchoChar((char)0); 
        PWField.setText("Password");
        PWField.setForeground(new Color(153,153,153));
    }
    }                                 

    private void CFFieldFocusGained(java.awt.event.FocusEvent evt) {                                    
    String pass = new String(CFField.getPassword());
    if (pass.equals("jPasswordField1") || pass.equals("Password")) {
        CFField.setText("");
        CFField.setEchoChar('●'); 
        CFField.setForeground(Color.BLACK);
    }   
    }                                   

   
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> new RegisterPage().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPasswordField CFField;
    private javax.swing.JTextField EField;
    private javax.swing.JTextField FNField;
    private javax.swing.JTextField LNField;
    private javax.swing.JTextField PNField;
    private javax.swing.JPasswordField PWField;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JTextField SNField;
    private javax.swing.JTextField UNField;
    private javax.swing.JButton aboutUsButton;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JComboBox<String> yearLevel;
    // End of variables declaration                   
}
